server:
  port:
    9002

# postgresql 설정
spring:
  application:
    name:
      back-work
      
  sql:
    init:
      platform: postgresql
      mode: always #never # always
      schema-locations:
      - classpath:schema.sql
      data-locations:
      - classpath:data.sql
      
  datasource:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: "viprghj2730!"
      url: jdbc:postgresql://localhost:5432/back_work
    
  jpa:
      defer-datasource-initialization: true
      
  zipkin:
    base-url: http://localhost:9412


# Mybatis 설정
mybatis:
  type-aliases-package: kr.co.dbinc.back_work.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
