server:
    port:
     9002
# postgresql \uc124\uc815
spring:
  application:
    name:
      back-work
  sql:
    init:
       platform:postgresql
       mode:always
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "viprghj2730!"
    url: jdbc:postgresql://localhost:5432/back_work
    
  jpa:
    defer-datasource-initialization: true


# Mybatis \uc124\uc815
mybatis:
 
  type-aliases-package: kr.co.dbinc.back_work.model
 
  mapper-locations: classpath:mapper/*.xml
  
  configuration:
    map-underscore-to-camel-case: true
    
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # \uc11c\ubc84\uc5d0 \ub530\ub77c \ub2e4\ub974\uac8c \uc124\uc815